# Generated by Django 3.2.3 on 2021-05-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='name',
        ),
        migrations.AddField(
            model_name='picture',
            name='user_id',
            field=models.IntegerField(default=255, max_length=255),
            preserve_default=False,
        ),
    ]
