# Generated by Django 3.2.3 on 2021-05-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0005_auto_20210522_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
