# Generated by Django 3.2.3 on 2021-05-24 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0006_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderMarkets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField()),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('service_type', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='picture',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_id',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('relation', models.CharField(default='', max_length=255)),
                ('is_sended', models.CharField(default='0', max_length=255)),
                ('service_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signin.sendermarkets')),
            ],
        ),
    ]
