# Generated by Django 3.2.3 on 2021-05-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0007_auto_20210524_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_text',
            field=models.TextField(default=''),
        ),
    ]
