# Generated by Django 3.2.3 on 2021-05-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0009_alter_sender_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='service_id',
            field=models.IntegerField(),
        ),
    ]
